// ACTION TYPES
export const FIND_ONE = "FIND_ONE";
export const FINDING_ONE = "FINDING_ONE";
export const FOUND_ONE = "FOUND_ONE";
export const FIND = "FIND"; // 2
export const FINDING = "FINDING"; // 1
export const FOUND = "FOUND"; // 3
export const ADD = "ADD";
export const ADDING = "ADDING";
export const ADDED = "ADDED";
export const DESTROY = "DESTROY";
export const DESTROYING = "DESTROYING";
export const DESTROYED = "DESTROYED";
export const PATCH = "PATCH";
export const PATCHING = "PATCHING";
export const PATCHED = "PATCHED";
export const UPDATE = "UPDATE";
export const UPDATING = "UPDATING";
export const UPDATED = "UPDATED";
export const REFRESH = "REFRESH";
export const REFRESHING = "REFRESHING";
export const REFRESHED = "REFRESHED";
export const ERROR = "ERROR";
export const SET_ONE = "SET_ONE";
export const REMOVE_ONE = "REMOVE_ONE";
export const SET_LIST = "SET_LIST";
export const REMOVE_LIST = "REMOVE_LIST";

export const FINDING_LIST = "FINDING_LIST";
export const FOUND_LIST = "FOUND_LIST";
export const SET_LIST_RESULT = "SET_LIST_RESULT";
export const SET_LIST_PAGE = "SET_LIST_PAGE";
export const SET_LIST_COUNT = "SET_LIST_COUNT";